// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject

package wire

import (
	"github.com/tony-zhuo/rule-engine/service/apis/engine/controller"
	"github.com/tony-zhuo/rule-engine/service/apis/engine/initialize"
	"github.com/tony-zhuo/rule-engine/service/apis/engine/usecase"
	cepMemory "github.com/tony-zhuo/rule-engine/service/base/cep/repository/memory"
	cepUsecase "github.com/tony-zhuo/rule-engine/service/base/cep/usecase"
	ruleUsecase "github.com/tony-zhuo/rule-engine/service/base/rule/usecase"
)

func InitializeEngineController(conf *initialize.Conf) *controller.EngineController {
	store := cepMemory.NewMemoryStore()
	ruleUC := ruleUsecase.NewRuleUsecase()
	cepUC := cepUsecase.NewCEPUsecase(store, ruleUC)
	engineUC := usecase.NewEngineUsecase(ruleUC, cepUC)
	return controller.GetEngineController(engineUC)
}
